export class Field {
    constructor(
      public id: number,
      public form_id: number,
      public label: string,
      public description: string,
      public form_field_name: string,
      public short_id: number,
      public field_type: string,
      public size: number,
      public validation_mask: string,
      public dropdown_name: string,
      public selection_options: string,
      public lookup_scope_id: number,
      public lookup_list_id: number,
      public lookup_dependencies: string,
      public lookup_source_field: string,
      public timer_duration: string,
      public timer_react_action: string,
      public tag_button_text: string,
      public required: boolean,
      public readonly: boolean,
      public visibility: string,
      public role_restriction_id: number,
      public group_name: string,
      public first_day_active: Date,
      public last_day_active: Date,
      public show_this_field_on_default_table_view: boolean,
      public url_timer_reset: string,
      public created_by: number,
      public created_at: Date,
      public updated_at: Date,
      public deleted_at: Date
    ) {}
  }